project:
  type: website
  output-dir: ../docs

website:
  title: "SOC-N100"
  repo-url: "https://github.com/evictionresearch/SOC-N100-Housing-Precarity-2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Syllabus
        href: syllabus.qmd
      - text: Resources
        href: resources.qmd
      - text: Learn R
        href: learn_r.qmd
      - text: RStudio
        href: https://r.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fevictionresearch%2FSOC-N100-Housing-Precarity-2026&urlpath=rstudio%2F
        target: _blank
    tools:
      - icon: r-circle-fill
        href: https://r.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fevictionresearch%2FSOC-N100-Housing-Precarity-2026&urlpath=rstudio%2F
        aria-label: RStudio
        target: _blank
      - icon: github
        href: https://github.com/evictionresearch/SOC-N100-Housing-Precarity-2026
        target: _blank

format:
  html:
    theme:
      cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
