---
title: "Syllabus"
subtitle: "Housing Precarity and Displacement: Racial and Gender Inequality in Gentrification and Eviction"
toc: true
published: "Summer 2025"
published-title: Term
author:
    - Tim Thomas
    - <timthomas@berkeley.edu>
author-title: Instructor
abstract: "This course introduces students to the intersecting crises of eviction, displacement, and gentrification through data-driven analysis. Using the U.S. Census and R programming, you’ll learn to quantify racial inequality, track segregation patterns, and map gentrification’s impact on vulnerable communities. Through weekly lectures, coding labs, and interactive online modules, we’ll explore how housing precarity disproportionately affects marginalized groups while building practical skills in R and data visualization. By term’s end, you’ll create dynamic maps and interactive dashboards that reveal hidden stories behind eviction trends, rent burden disparities, and neighborhood change – equipping you to communicate complex social issues through both sociological theory and cutting-edge data tools. Designed for beginners in coding, this fully online course emphasizes real-world applications, with case studies ranging from urban displacement in coastal cities to rural housing instability."

# "Residential displacement is the involuntary relocation of residents from their homes or neighborhoods due to factors beyond their control. This can occur when households are forced to move because of evictions, rent increases, building demolitions, or other changes that make their current housing unaffordable or uninhabitable. The consequences of displacement are dire, leading to long-term housing and financial instability; worse health outcomes; and reinforces racial, gender, and economic disparities. Today, a large share of the United States is facing housing precarity and are at great risk of displacement. Roughly 50% of renters are rent-burdened (paying more than 30% of their income to rent), about 1/3rd (32%) of adults are likely to miss next month’s rent or mortgage payment, and homelessness is higher now than it was during the 2008 Great Recession. Institutions are determined to understand the prevalence and risk of displacement because it affects both households at the micro level and shapes cities and regions at the macro level. But how do we measure displacement and what can be done about it?
# <br><br>
# This course will help you understand the origins, drivers, and indicators of displacement in the United States as well as train you on how to measure and visualize it for a stakeholder audience. You will be given an introduction to the leading research on displacement and will exercise your computational social science skills to conduct data wrangling, spatial analysis, statistical modeling, and visualization. The course is also designed to prepare you for working in groups on a team project that will satisfy your supervisor (me) and your company’s client.  
# <br><br>
# Each week will serve as a building block for the final project—meaning in-class participation, readings, and on-time assignments are vital requirements. Classes will begin with a mini-lecture on the week’s topic followed by in-class exercises on how to use the U.S. Census as a primary data source to measure displacement drivers and indicators. In-class exercises will set you up to work independently on two assignments. The final group project and presentation will combine what you’ve learned so you can build an analysis on a pressing topic that may interest governmental stakeholders. "
abstract-title: ""
theme: cosmo
---

### Course Culture

This course brings together students from diverse backgrounds to examine housing inequality through data analysis in R. We create a collaborative, listening-centered environment where all voices are valued and where we approach housing data with critical consciousness about systemic racism and gentrification's human impacts.

**Our shared commitments**:

-   **Listen first** - We begin with the experiences of communities affected by housing displacement before analyzing statistics
-   **Intersectional analysis** - We examine how race, gender, and class intersect to create different experiences of housing precarity
-   **Respectful dialogue** - We engage difficult conversations about inequality with professionalism and care for one another
-   **Collective learning** - We develop data skills together, supporting each other's technical and critical learning

Creating brave space: We recognize that housing data reveals uncomfortable truths about displacement and discrimination. We commit to supporting classmates who may be personally affected by housing insecurity while holding ourselves accountable for learning that serves rather than extracts from communities.

If you have concerns about classroom environment or need support, please reach out to me to discuss how we can better foster inclusive learning for everyone.

<!-- ### Mode of Instruction -->

<!-- This course is structured as a flipped class, meaning that you will first be encountering new concepts in statistics and data science *outside* of class. Class time is dedicated to expanding on the work you've done outside of class by working through questions solo, in groups, and as a class. -->

<!-- ```{=html} -->
<!-- <!-- -->
<!-- The reason that this course is structured in this manner is that applied data science is a complex field that unites scientific thinking, computing, mathematics, and an understanding of the context of the data. We will be able to tackle more interesting and challenging questions if we make room during class time to work on them while we're all in the same place. -->
<!-- -->
<!-- ``` -->

<!-- #### Before class -->

<!-- **It is your responsibility to become familiar with the topics that appear in the course notes and to work through the reading questions on Gradescope by 11:59 pm Monday (for Tues/Weds class) and 11:59 pm Wednesday (for Thurs/Fri class)**. You're encouraged to experiment to find the method that works best for you: downloading the notes as a pdf and making notes on them, asking and answering questions over the class forum, etc. -->

<!-- #### During class on Tue/Wed and Thu/Fri -->

<!-- Class time (2 hrs) will be spent on a range of activities, but the most common will be concept questions (using Poll Everywhere) and working through components of your Problem Sets and Labs. Therefore, the most efficient way to complete your assignments is to be an active participant in class. Attendance is expected on these class days. -->

<!-- #### During class on Monday -->

<!-- Monday is shorter (1 hr) class that alternates between: -->

<!-- -   Workshops: less-structured class dedicated to finishing up work on your assignments -->
<!-- -   Quizzes: see information on quizzes below. -->

<!-- ```{=html} -->
<!-- <!-- -->
<!-- #### Plenary lectures -->

<!-- Several times during the semester, the course will be hosting a special guest to give a lecture to all sections of Stat 20. These speakers are preeminent scientists and data scientists from academia or industry who will speak about how the ideas and tools from Stat 20 are used in and impact the real world. These plenary lectures will be held outside of class time in the evening and the schedule will be announced during the semester.  -->

<!-- As a part of the graded assignments for the class **you will be asked to attend three lectures outside the class and hand in a small written assignment about each**. These lecture could be the Stat 20 plenary lectures or they could be from another event; the only restriction is that they have to be related to data science. -->
<!-- --> 
<!-- ``` -->

<!-- #### Group tutoring -->

<!-- Tutors will offer group tutoring sessions several times each week. This is an opportunity to finish up any assignments that you've started in class or review any topics that are confusing for you. Each group tutoring session will be staffed by 2-4 tutors. You're welcome to attend any session that works well for your schedule. -->

<!-- Group tutoring is a great place to go to meet other students and collaborate on assignments with tutors on hand to help you get unstuck. -->

<!-- #### Instructor Office Hours -->

<!-- The instructors will offer office hours each week across a range of times. We ask that you only visit the office hours of your instructor, but you are welcome to visit the tutoring sessions of *any* tutors, not just the ones who work in your section. We may adjust the office hour and group tutoring sessions schedule throughout the semester as we understand student needs and preferences. Please check the office hours tab on the syllabus page to see the times of the various office hour/group tutoring sessions. -->

<!-- Office hours are an opportunity to chat one-on-one with your instructor. Please come to office hours! Coming to office hours does not send a signal that you are behind or need extra help. On the contrary, coming to office hours early and often tends to co-occur with success in the course. Instructors are happy to chat about the course material, statistics in general, careers in statistics, and whatever other statistics or data science topics are on your mind! -->

<!-- #### Don't come to class if you're sick! -->

<!-- Maintaining your health and that of the Berkeley community is of primary importance to course staff, so if you are feeling ill or have been exposed to illness, whether it's COVID-19 or something else, please do not come to class. All of the materials used in class will be posted to the course website. You're encouraged to reach out to fellow students to discuss the class materials or stop by group tutoring or office hours to chat with a tutor or the instructor. -->

### Materials

The primary materials for the course are available on this website. I'll teach you everything you need to know!

#### RStudio

The software that we'll be using for our data analysis is the free and open-source language called R that we'll be interacting with via software called RStudio. As a Berkeley student, you have your own version of RStudio waiting you on a special [data hub](https://stat20.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fevictionresearch%2FSOC-N100-Housing-Precarity&urlpath=rstudio%2F). This data hub syncs the class materials, giving you access to most of what you need. Most students taking this course have no experience programming; I'll teach you everything you need to know!

### Workload
*   4 hours of class time (2 hours of lecture, 2 hours of lab)
*   expect 12 hours of work outside of class after week 1

### Instruction Mode
This course will be held on Zoom with recordings posted after each class. 

### Course Requirements and Assignments

Your grade has three components, which have the following weights: 

1. Class participation 20%
2. Assignments (#1 = 20%, #2 = 20%) 40%
3. Final group project 40%

#### Class participation (20%)

Participation in class is an important part of your learning experience and a vital skill in the working world. Participation in class also gives me richer information about your grasp of the class material and helps me make adjustments where necessary. Attendance makes up 10% for class participation and the remaining 10% is based on your participation - in-class quizzes, contributing to class discussions, asking questions, offering up potential solutions to problems, presenting a solution to an assignment, volunteering to present, and overall engagement and enrichment of the class.

A good contribution to class discussion is a comment that possesses one or more of the following properties. (1) It offers a different and unique, but relevant, insight to the issue; moves the discussion and analysis forward to generate new insights. (2) It builds on the preceding discussion; relates to a personal anecdote or experience in a way that helps to illuminate the ideas being discussed. (3) It uses logic, evidence, and creative thinking (argument), so that it is more than merely an expression of an opinion or feeling (assertion).

#### Assignments (40%). 

For each assignment you will submit:

* R code script that is replicable by the grader, 
* a brief write up explaining your assignment with plots and context, and 
  * Include one or more introductory paragraphs summarizing what you are analyzing and your overall findings. 
  * Text and plots walking the reader through a more detailed understanding of what you found. Make sure to describe your plots. 
  * Summary conclusion and analytic insights (i.e., what the data is telling you).
* URL links to any and all AI usage. 
  * In you code, put the URL in comments next to the relevant area. 
  * In your write up, put the URL in footnotes near the section or text in which you used AI. 
  * [*See AI policy below for more info.*](#ai-policy)

These assignments will be graded on using the scale below. Anything above a D will pass. No late assignments will be accepted. You can volunteer to present a 5-minute demo of your assignment in class.

#### Final group project (40%). 

For your final group project you and 2-3 of your peers will choose a city or county and come up with a research question you can answer with one of the datasets from the class that tests at least two hypotheses about the disparate impact or unique problem of displacement in that area. You will need to do some research about your chosen area and may even need to do some exploratory analysis of the area to see what might be a suitable research question and driver of displacement. For example, in Marin County, CA high rents are displacing the county’s workforce-age adults and young families, resulting in school closures and deterring needed residents to keep the county sustainable. Another example is Salt Lake City’s most affordable neighborhoods are also experiencing high rates of displacement, meaning there is no where for displaced residents to move to that is affordable. Find something that would be compelling for the city or county to know about the problem of displacement in their area. 

* You will submit a final report, R code, and a short slide presentation (no longer than 10 slides) showcasing your question, your methods and key results. 
* On the last day you will present your project to the class. 

### Course Grading 

A+ 97+ | A 93-96 | A- 90-92

B+ 87-89 | B 83-86 | B- 80-82

C+ 77-79 | C 73-76 | C- 70-72

D+ 67-69 | D 63-66 | D- 60-62

F 0-59

### Late work policy

No late work will be accepted.

### AI Policy

AI is allowed and encouraged in this course as it is crucial to learn how to use these tools effectively for your future work. However, it is vital to recognize both the strengths and limitations of AI to avoid jeopardizing your projects and future career. Here are some key considerations:

*Understanding AI's Role*

1. *Information Synthesis*: AI excels at synthesizing information but does not create new knowledge. It serves as a broad assistant for research, writing improvement, and coding tasks.
2. *Limitations of Training Data*: AI models are constrained by their training data and cannot generate truly novel ideas or content beyond this scope.
3. *Potential for Errors*: AI hallucinations and misinterpretations are real concerns. Always critically evaluate and verify AI-generated content.

*Effective AI Usage*

1. *Prompt Engineering*: The quality of AI output heavily depends on the quality of input. Craft clear, specific prompts to get the best results.
2. *Human Expertise*: You are the domain expert. Ensure that AI is working for you and aligning with your goals and expectations.
3. *Fact-Checking*: Always verify AI-generated information, especially for recent events or specialized topics.

*Ethical Considerations*

1. *Attribution*: When using AI-generated content, properly attribute it in your work.
2. *Academic Integrity*: Use AI as a tool for learning and productivity, not as a substitute for your own critical thinking and analysis.
3. *Bias Awareness*: Be mindful of potential biases in AI-generated content and strive for diverse perspectives.

*Be vigilant about model changes moving forward:* As AI advances, be aware of both improvements to models as well as possible problems (i.e., increasing censorship, how it was trained, developer intent, etc.). 

In this class you will use [perplexity.ai](https://perplexity.ai) because it allows you to test and use multiple language models (e.g., OpenAI, Claude, Lamma, and a few more) and searches the web to find the most recent information about a topic. Access to the web supplements its knowledge and usefulness. Sign up for a discounted perplexity pro account at <https://plex.it/referrals/OXHAU39O>

Do not use any other AI platform without permission. You will be required to provide URLs to your use of Perplexity so we can understand your use of it and help develop your skills. 

*Responsible AI Use*

1. *Transparency*: Be open about your use of AI tools in your work.
2. *Iterative Approach*: Use AI as part of an iterative process. Start with creating some content and then ask AI to refine and improve results with your own expertise.
3. *Skill Development*: Focus on developing skills in prompt engineering, critical evaluation, and effective integration of AI-generated content.

*Reporting Issues*

If you encounter any problems or have concerns about AI use in the course, please report them to the instructor promptly.

By following these guidelines, you'll be better equipped to harness the power of AI while maintaining the integrity and quality of your academic work in computational social science.

### Code of Conduct

Students and the instructor will abide by the [UC Berkeley Code of Conduct](https://ethics.berkeley.edu/code-conduct).

### Primary Datasets & Tools

The American Community Survey (ACS) is an ongoing survey conducted by the U.S. Census Bureau that provides vital information about the United States and its people. Released annually, the ACS covers a broad range of topics including social, economic, housing, and demographic characteristics of the U.S. population. Some of the primary variables used to measure displacement that are derived from the ACS include housing characteristics, rent, racial and ethnic compositions, incomes, and migration. 

tidycensus is an R package that provides a user-friendly interface to access ACS data directly within the R environment. It allows users to retrieve ACS data in a tidy format, ready for analysis with tidyverse tools. With tidycensus, you can easily download ACS data for various geographic levels (e.g., states, counties, census tracts) and years, and include spatial data for mapping purposes.

### Disabled Student Program (DSP)

UC Berkeley is committed to creating a learning environment that meets the needs of its diverse student body including students with disabilities. If you anticipate or experience any barriers to learning in this course, please feel welcome to discuss your concerns with me.

If you have a disability, or think you may have a disability, you can work with the Disabled Students' Program (DSP) to request an official accommodation. The Disabled Students' Program (DSP) is the campus office responsible for authorizing disability-related academic accommodations, in cooperation with the students themselves and their instructors. You can find more information about DSP, including contact information and the application process here: dsp.berkeley.edu. If you have already been approved for accommodations through DSP, please meet with me so we can develop an implementation plan together."

Students who need academic accommodations or have questions about their accommodations should contact DSP, located at 260 César Chávez Student Center. Students may call 642-0518 (voice), 642-6376 (TTY), or e-mail dsp@berkeley.edu(link sends e-mail).

<!-- ### Course communication -->

<!-- #### bCourses -->

<!-- We will use bCourses to disseminate announcements for the entire class, such as final exam information. -->

<!-- #### Discussion forum -->

<!-- The official discussion forum for the class will be hosted on [Ed](https://www.edstem.org). Ed is a forum to ask and answer questions with your fellow students and course staff. It's an indispensable resource for learning from your peers and seeking help from tutors and instructors. -->

<!-- If you have a question for staff, create a new post and mark it as "private" and it will go only to course staff. This is the best option to contact us if you have a personal concern. If your question does not include personal information and can be answered by other students, make sure it is public. -->

<!-- In a course this large, the instructors have a difficult time responding to individual emails, so please use the class forum or visit office hours if you wish to contact us! -->

<!-- #### Course website -->

<!-- All of the assignments will be posted to the course website at <https://stat20.org>. This also holds the course notes, the syllabus, and links to Gradescope, Ed, and RStudio. -->

<!-- ### Assignments, Exams, and Grading -->

<!-- #### Turning-in assignments -->

<!-- You will be turning in your assignments on a platform called [Gradescope](https://www.gradescope.com/). This is also the platform where your assignments will be graded, so you can return there to get feedback on your work. You are welcome to file a regrade request if you notice that we made an error in applying the rubric to your work. -->

<!-- #### Labs -->

<!-- Labs are long-form assignments designed to apply the concepts from the lecture notes in the cause of doing an analysis of real data. This will involve both writing code and communicating your thoughts and findings in English. We'll be working through some problems from the labs in class, but you may have to complete them on your own outside of class time. Some labs will be turned in individually; some will be turned in as groups. -->

<!-- Labs are to be submitted as PDF files. These PDFs will be generated by rendering Quarto Documents (.qmd files) to HTML and then exporting the HTML into a PDF. Don't worry if you're not familiar with the Quarto Document as we will teach you about it! -->

<!-- We will be assessing most questions on labs for correctness but for others we will be giving credit based on completion. -->

<!-- #### Problem Sets -->

<!-- During class, we will give you a second engagement with the day's material in the form of a worksheet. These worksheets will run like traditional homework problems and drill the concepts in the reading notes rather than asking you to apply the concepts with a data set, like the lab does. -->

<!-- ```{=html} -->
<!-- <!-- -->
<!-- The problem sets will be procured completely from these in-class worksheets and released in one or two week intervals. -->
<!-- --> 
<!-- ``` -->

<!-- #### Reading Questions -->

<!-- Reading questions serve to check your understanding and engagement while going through the lecture notes prior to class. There will be a handful of questions per lecture note. These questions be a mix of multiple choice, short answer, and coding questions. You can answer them directly on Gradescope. The reading questions will be **due 11:59 pm on Mondays (for the Tuesday/Wednesday lectures) and Wednesdays (for the Thursday/Friday lectures)**. -->

<!-- ```{=html} -->
<!-- <!-- -->
<!-- #### Plenary Lecture Reviews -->

<!-- An important way to engage with new ideas and people at a University is to attend guest lectures. Stat 20 will host 3-5 such lectures over the course of semester and will also provide a list of guest lectures in other departments that focus on topics related to probability, statistics, and data science. -->

<!-- A plenary lecture review is a written assignment that details the background of the speaker, the question they address, the tools, data, and methods they use, and their key findings. You will be asked to submit three such lecture reviews over the course of the semester based on the lectures that you have chosen to attend. These lecture reviews will be due at the end of the semester. -->
<!-- --> 
<!-- ``` -->

<!-- #### Quizzes -->

<!-- Quizzes reinforce the most important concepts from the lecture notes and provide you the opportunity to work through misunderstandings of concepts with peers and the instructor. -->

<!-- There is both an *individual* and *group* component to the quiz. -->

<!-- The *individual* component will last \~25 minutes. You are allowed one, A4, one-sided handwritten sheet of notes. The *group* component will take place immediately after the individual component has been completed and will last \~15 minutes. Your final (composite) quiz grade will be the average of your group and individual quiz scores. -->

<!-- #### Exam -->

<!-- The final exam will be held in person during finals week. The time and date is **Thursday, May 9 from 7-10pm** (apologies). -->

<!-- #### Grading -->

<!-- Your final grade in the course will be computed as follows: -->

<!-- -   Labs 35% -->
<!-- -   Reading Questions: 3% -->
<!-- -   Quizzes 25% -->
<!-- -   Problem sets 7% -->
<!-- -   Final 30% -->

<!-- The grades will not be curved (\> 90% is some kind of A, etc.). -->

<!-- In order to provide flexibility around emergencies that might arise for you throughout the semester (for example, missing a quiz due to COVID), we will apply for everyone: -->

<!-- -   one emergency drop for quizzes\ -->
<!-- -   one emergency drop for labs -->
<!-- -   two emergency drops for problem sets -->
<!-- -   two emergency drops for reading questions. -->

<!-- This means, for example, that we will drop your lowest quiz score before computing your average score across all quizzes. -->

<!-- ### Policies -->

<!-- #### Accomodations for students with disabilities -->

<!-- Stat 20 is a course that is designed to allow all students to succeed. If you have letters of accommodations from the Disabled Students’ Program, please share them with your instructor as soon as possible, and we will work out the necessary arrangements. -->

<!-- #### Late Work -->

<!-- Unfortunately, with a class of this size, we are unable to keep track of and grade submissions of labs, reading questions, and problem sets that come in very late. If you narrowly miss the standard deadline, you will still be able to submit within an hour for a small penalty (5% reduction in score). If you don't submit within an hour you can still submit for a larger penalty (30% reduction). -->

<!-- ### Collaboration policy -->

<!-- You are encouraged to collaborate with your fellow students on problem sets and labs, but the work you turn in should reflect your own understanding and all of your collaborators must be cited. The individual component of quizzes, reading questions, and exams must reflect only your work. -->

<!-- Researchers don't use one another's research without permission; scholars and students always use proper citations in papers; professors may not circulate or publish student papers without the writer's permission; and students may not circulate or post non-public materials (quizzes, exams, rubrics-any private class materials) from their class without the written permission of the instructor. -->

<!-- The general rule: you must not submit assignments that reflect the work of others unless they are a cited collaborator. -->

<!-- The following examples of collaboration **are** allowed and in fact encouraged! -->

<!-- -   Discussing how to solve a problem with a classmate. -->
<!-- -   Showing your code to a classmate along with an error message or confusing output. -->
<!-- -   Posting snippets of your code to the discussion forum when seeking help. -->
<!-- -   Helping other students solve questions on the discussion with conceptual pointers or snippets of code that doesn't whole hog give away the answer. -->
<!-- -   Googling the text of an error message. -->
<!-- -   Copying small snippets of code from answers on Stack Overflow. -->

<!-- The following examples are **not** allowed: -->

<!-- -   Leaving a representation of your assignment (the text, a screenshot) where students (current and future) can access it. Examples of this include websites like course hero, on a group text chain, over discord/slack, or in a file passed on to future students. -->
<!-- -   Accessing and submitting solutions to assignments from other students distributed as above. This includes copying written answers from other students and slightly modifying the language to differentiate it. -->
<!-- -   Googling for complete problem solutions. -->
<!-- -   Working on the reading questions or individual quizzes in collaboration with other people or resources. These assignments must reflect individual work. -->
<!-- -   Submitting work on an quiz or final that reflects consultation with outside resources or other people. These assessments must reflect individual work. -->

<!-- If you have questions about the boundaries of the policy, please ask. We’re always happy to clarify. -->

<!-- #### Violations of the collaboration policy -->

<!-- The integrity of our course depends on our ability to ensure that students do not violate the collaboration policy. We take this responsibility seriously and forward cases of academic misconduct to the Center for Student Conduct. -->

<!-- Students determined to have violated the academic misconduct policy by the Center for Student Conduct will receive a grade penalty in the course and a sanction from the university which is generally: (i) First violation: Non-Reportable Warning and educational intervention, (ii) Second violation: Suspension/Disciplinary Probation and educational interventions, (iii) Third violation: Dismissal. -->

<!-- And again, if you have questions about the boundaries of the collaboration policy, please ask! -->

<!-- ### Frequently Asked Questions -->

<!-- 1.  What should I do if I'm on the waitlist? -->

<!--     Attend *both* lecture and section (remember, we are teaching it as *one* two hour class), and submit all assignments on time. Visit your instructor on the first day of class so you can be added to the course Ed and Gradescope. -->

<!-- 2.  Are class sessions recorded? -->

<!--     No. Class sessions feature a mix of group problem solving, activities, and discussion and don't lend themselves to recording. The course notes are the main reference source for the course. Any materials used during the class session will be posted to the course website. -->

<!-- 3.  Is attendance required? -->

<!--     No, but it is difficult to succeed in this course if you are not regularly attending class. Class sessions are designed to be an effective and efficient format to make progress on important assignments. Plus, it's a great way to meet your fellow students and learn from one another. This class is very unique in that regard. -->

<!--     If you can't attend due to a religious observance, athletic competition, or something similarly important, don't worry. Just reach out to us via a private Ed post, and we can let you know what to keep tabs on during the time you're away. -->

<!-- 4.  Are time conflicts allowed? -->

<!-- Stat 20 does not allow students to enroll with time conflicts. -->

<!-- 5.  What if I join the class late? -->

<!--     If you join the class within the first two weeks, read the syllabus and lecture notes, take a look at Gradescope to get a sense of any assignments that may have already passed, and visit office hours to check that you're up to date with things. The first two weeks of material are very important so you must be able to make up assignments. -->

<!--     After two weeks into the semester, you'll have too much material that you'll need to make up, so you will have to wait to a subsequent semester to take Stat 20. -->

<!-- ### Campus Resources -->

<!-- If you ever need someone to talk to about anything that you're going through, please feel to reach out to the instructors. For some topics, the tutors might be an even better resource because they are students just like you. Tutors can also tell you what being an Academic Student Employee (ASE) is like. -->

<!-- With regards to reports of sexual misconduct/violence/assault, you may speak with us as well, but know that we will need to report our discussion to the Title IX officer. This is detailed below. -->

<!-- > *As UC employees, the instructors (and tutors) are "Responsible Employees" and are therefore required to report incidents of sexual violence, sexual harassment, or other conduct prohibited by University policy to the Title IX officer. We cannot keep reports of sexual harassment or sexual violence confidential, but the Title IX officer will consider requests for confidentiality. Note that there are confidential resources available to you through UCB's PATH to Care Center, which serves survivors of sexual violence and sexual harassment; call their 24/7 Care Line at 510-643-2005.* -->

Below are some campus resources that may be helpful for you:

-   [Berkeley Supportal- great place to start](https://supportal.berkeley.edu)
-   [Disabled Students' Program](https://dsp.berkeley.edu)
-   [University Health Services](https://uhs.berkeley.edu)
-   [UCB Path to Care](https://care.berkeley.edu)
-   [Student Learning Center](https://slc.berkeley.edu/home)
-   [Berkeley International Office](https://internationaloffice.berkeley.edu)
-   [Ombuds Office for Students and Postdoctoral Appointees](https://studentaffairs.berkeley.edu/ombuds-office-for-students-postdoctoral-appointees/)
-   [Gender Equity Resource Center](https://cejce.berkeley.edu/geneq)
-   [Center for Educational Justice & Community Engagement](https://cejce.berkeley.edu)
-   [UHS Counseling and Psychological Services (CAPS)](https://uhs.berkeley.edu/caps)
-   [Campus Academic Accommodations Hub](https://evcp.berkeley.edu/programs-resources/academic-accommodations-hub)
-   [ASUC Student Advocate’s Office](https://advocate.berkeley.edu)
-   [Basic Needs Center](https://basicneeds.berkeley.edu/home)
-   [ASUC Mental Health Resources Guide](https://asuc.org/wp-content/uploads/2018/02/Mental-Health-Resources.pdf)
